In [110]:
import numpy as np

a= [2,4,5]

aa = np.array(a)
aa

array([2, 4, 5])

In [111]:
import numpy as np
# jupyter 노트북 키는법 : 파일.ipynb 콘다 환경 설정 되어있어야하는듯?

# for문 없이 2차원 배열을 만들기 때문에 더 빠름.
a = np.arange(15).reshape(3,5)
print(a)



# ex.코드가 길어질때 어딨는지 찾기위해 이렇게 쓸 수도 있음
print(a.shape) # 형태를 확인
print(a.dtype.name) # 자료형을 확인
print(a.itemsize)
print(a.size) # 크기를 확인인

# np.array를 선언할때 ()로 꼭 감싸줘야함
b = np.array([5,7,8])
print(b)

c = np.array([1,'two',3,4])
print(c)

# 자료형?
a = np.array([1.2, 3.5, 5.1])
print(a.dtype)
print(0)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
int32
4
15
[5 7 8]
['1' 'two' '3' '4']
float64
0


In [112]:
import numpy as np

arr = np.arange(10)
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [113]:
import numpy as np

arr_slice = arr[5:8]
arr_slice

arr_slice[1] = 12345
arr_slice

arr_slice[:] = 64
arr_slice
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [114]:
# array 를 만드는 함수들
a2 = np.zeros(3) # 1 차원 배열을 변수만큼의 0으로 생성
a2 # array([0., 0., 0.])

a3 = np.ones(3) # 1 차원 배열을 변수만큼의 1로 생성
a3 # array([1., 1., 1.])

k1 = np.eye(3) # x 행 x 열 단위행렬 생성
k1 # array([[1., 0., 0.],
   #       [0., 1., 0.],
   #       [0., 0., 1.]])

# 배열의 차원 형태 변경
c = np.arange(1,5) 
c # array([1, 2, 3, 4]) / 1차원 배열임
c.shape = (2,2) # c 배열의 형태를 2행 2열로 바꿈
c # array([[1, 2],
  #        [3, 4]])

array([[1, 2],
       [3, 4]])

In [115]:
c = np.array([1,2,3,4])
c
c.shape = (2,2)
c

c.shape=(4,)
c

# 2행 2열을 3으로 채움.
c=np.full((2,2), 3)
c

array([[3, 3],
       [3, 3]])

In [116]:
na = np.array([1,2,3,4,5,6,7,8])
na
na.reshape(2,4) # 데이터 크기만 맞으면 행열을 바꿀 수 있음

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [117]:
a = na.reshape(2,4)
a[1,1]
# 위 아래 같음
a[1][1]

6

In [118]:
array = np.array([
    [[0,1,2,3],[4,5,6,7],[8,9,10,11]],
                 [[0,1,2,3],[4,5,100,7],[8,9,10,11]]
                  ])
array
#               텐서가 2, 3행 4열
# array.shape # (2,3,4)의 3차원 배열

# array[1,1,2]

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[  0,   1,   2,   3],
        [  4,   5, 100,   7],
        [  8,   9,  10,  11]]])

In [119]:
k = np.random.random((2,2))
k

array([[0.25015617, 0.70795085],
       [0.79254166, 0.17267805]])

In [120]:
x = np.array([[1,2], [3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

x+y
# 위 아래 같음.
xy_sum = np.add(x,y)
xy_sum

x-y
# 위 아래 같음.
xy_sub = np.subtract(x,y)
xy_sub

x*y
# 위 아래 같음.
xy_mul = np.multiply(x,y)
xy_mul

x/y
# 위 아래 같음.
xy_div = np.divide(x,y)
xy_div

# 제곱근 배열
x_sqrt = np.sqrt(x)
x_sqrt

# 배열의 연산은 shape도 맞춰야 한다

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [121]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

# 벡터의 내적 : 둘 다 결과 동일
v.dot(w)
vw_dot = np.dot(v,w)
vw_dot

# 행렬과 벡터의 곱 : 둘 다 결과는 rank1인 배열 동일
x.dot(v)
xv_dot = np.dot(x,v)
xv_dot

# 행렬곱 : 둘 다 결과는 rank2인 배열 동일
x.dot(y)
xy_dot = np.dot(x,y)
xy_dot

array([[19, 22],
       [43, 50]])

In [ ]:
a = [1,2,3]
b = [3,4,5]
type(a)

2*a

a+b
# 리스트라 배열 연산 헥갈림 주의
# 리스트의 연산은 뒤에 붙음

[1, 2, 3, 3, 4, 5]

In [ ]:
import numpy as np

a = np.array([1,2,3])
b = np.array([3,4,5])
type(a) # numpy.ndarray

2*a
a+b
# 배열의 연산은 같은 행과열의 값들의 연산이 이뤄짐.

array([4, 6, 8])

In [ ]:
c = np.array([[1,2,3],[4,5,6]])
c
c.size # 6 배열의 크기는 원소의 갯수인듯...
c.shape # 2행 3열 배열

d = np.arange(10).reshape(2,5) # 1부터 9까지 2행 5열의 배열 생성
d

e = np.arange(2,3,0.1) # 2에서 3 미만까지 0.1step으로 만듬
e

f = np.linspace(1.0,4.0,6) # 1.0이상 4.0 이하 0.6의 등간격 6원소 배열 생성

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [ ]:
a = np.zeros((2,2), int) # 데이터 타입을 int로
a
b = np.zeros((2,2), float) # 데이터 타입을 실수로
b

c = np.ones((2,2)) # 2by2 float
c

d = np.full((2,2), 7) # 2by2 7
d

e = np.eye((2)) # 단위 행렬 대각선으로 1
e

f = np.random.random((2,2)) # 2by2 랜덤flat
f

array([[0.94384004, 0.01299282],
       [0.89240601, 0.00775429]])

In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

a[0][0]
a[0,0]
a[1,2]

a[-1,-1] += 10 # 마지막행에 10을 더함
a[-1,-1] -= 10

a[1,:] # 1행의 모든 열
a[:,1] # 모든행의 1열
a[:2,:] # 0부터2미만 행의 모든 열
a[:,0:3:2] # 모든행의 0부터3미만의 열을 2의 간격으로
a[:,-1:-4:-2] # 모든행의 -4미만(현재는 모든 열)을 2간격으로 역순
a[:,[2,0,2,1]] # 모든행 3,0,2,1 열 순서로
a[[0,1,2], [0,1,2]] # [0,0], [1,1], [2,2] 원소

array([ 1,  6, 11])

In [199]:
a

a > 5 # 원소들이 조건에 따라 bool반환
a[a>5] # a의 배열에서 조건에 맞는 원소들만 반환

b = a[:] #a를 b에 shallow copy : 원본의 영향을 미침
b

b[b%2==0]

array([ 2,  4,  6,  8, 10, 12])

In [ ]:
c = np.array([[1,2,3],[4,5,6]])
c
d = np.arange(11,17).reshape(2,3)
d

c+d # 원소별 연산
c-d
c*d
c/d
c**2 # dtype=int32
np.sqrt(c)
np.dot(c,d.transpose()) # 행렬연산, 머신러닝할때 경사하강법에서 주로 다룰듯...
# transpose() = .T =  전치 : 행과 열을 바꿈 , 행렬 곱 조건을 맞추기 위해 사용함
np.dot(c.T, d) # 행렬연산
# 경사하강법 : 어떤 값을 최소화하기 위해 기울기를 따라 조금씩 내려가는 과정

array([[ 67,  72,  77],
       [ 92,  99, 106],
       [117, 126, 135]])

In [ ]:
list1 = [3, 5.6, 5,8,9,5]
array = np.array(list1)
array.var() # 분산 = 평균균

array.mean()
array.sum()
array.max()
array.min()
array.std() # 표준편차

4.022222222222223

In [ ]:
ar = np.array([1,2,3])
ar.dtype # int 32
# 정수의 기본형 int 32비트
# 실수의 기본형 float 64 실수 64비트

ar1 = np.array(['12','2','3'])
ar1.dtype # '<U2' 유니코드2

ar2 = np.array([1.5,2.0,3.5])
ar2.dtype # float 64

ar3 = np.array([1,2.9,3,'4'])
ar3.dtype # <U11 유니코드11

dtype('<U11')

In [ ]:
ar = np.array([False, True, False, False], dtype=np.int32) # 배열 dtype의 형변환
ar # false = 0, true = 1
ar.dtype

dtype('int32')

In [ ]:
# numpy user guide 사이트에서 공부하는게 나음 시판되는 책들이 이걸 기반으로 만듬

In [ ]:
# 1. 숫자 15에서 23까지 배열을 만들고 이를 3*3 행렬로 변환하여 출력
ar1 = np.arange(15,24).reshape(3,3)
ar1

평균 : 83.39999999999999, 표준편차 : 12.275483697190916
철수의 최종점수는 64.0


array([[ 6. , 40. , 18. ],
       [ 6. , 40. , 18. ],
       [31.2, 10. , 36. ],
       [16.2,  9. , 19.8]])

In [ ]:
# 2. 다음의 두 array를 만들고 위의 두 array를 이용해서 아래와 같은 값이 나오게
#  [1,2,3,4]
#  [5,6,7,8]
# 목표 : [f ,f , f, f]
ar1 = np.array([1,2,3,4])
ar2 = np.array([5,6,7,8])
ar1 > ar2

In [242]:
# 3. 아래와 같이 3학생의 중간고사 점수 , 기말고사 점수, 과제점수가 있다.
# (철수, 영희, 민재)
# 중간고사 = (15, 100, 45)
# 기말고사 = (78, 25, 90)
# 과제 = (81, 45,99)
# 각 중간, 기말, 과제점수의 가중치를 각각 0.4, 0.4, 0.2 를 부여하여 가중치의 합을 구하고, 거기에 기타점수 5점을 더하고자 한다.
# 이를 array를 이용해 계산하는 프로그램을 작성하라
# 요구사항 
# 1. 중간고사 평균과 표준편차를 출력하라
# 2. 철수의 최종점수는 얼마인지를 출력하라
ar_p = np.array(['철수', '영희', '민재'])
ar_s = np.array([[15, 100, 45],[15, 100, 45],[78,25,90],[81,45,99]], dtype=float)

ar_s[:3,:] *= 0.4
ar_s
ar_s[3:, :] *= 0.2
ar_s+=5
ar_s.std()

print(f'평균 : {ar_s[:1,0:].mean()},{ar_s[1:2,0:].mean()}, {ar_s[2:3,0:].mean()}, {ar_s[3:4,0:].mean()}, 표준편차 : {ar_s.std()}')
print(f'{ar_p[0]}의 최종점수는 {ar_s[:1,0:].sum()}')
# ar_s

평균 : 26.333333333333332,26.333333333333332, 30.733333333333334, 20.0, 표준편차 : 12.275483697190916
철수의 최종점수는 79.0


In [246]:
# 1. 1차원 배열 생성 및 연산
# 숫자 10 부터 30까지의 배열을 생성하고 ,배열 내 모든 값에 2를 곱한 결과를 출력
ar = np.arange(10,31)
ar*=2
ar

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52,
       54, 56, 58, 60])

In [248]:
# 2. 다차원 배열 생성 및 변환
# 숫자 0부터 15까지 포함하는 1차원 배열을 생성
# 이를 4*4 행렬로 변환
ar1 = np.arange(0,16)
ar1.shape = (4,4)
ar1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [249]:
# 3. 특정 조건에 맞는 값 필터링
# 1부터 20까지의 배열에서 짝수만 추출하여 새 배열을 생성
ar2 = np.arange(1,21)
ar2[ar2%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [290]:
# 4. 배열 연산 및 집계 함수 활용
# 임의의 3*3 배열을 생성
# 각 행의 합계와 평균 출력
ar3 = np.random.randint(1,10,(3,3))

# axis = 1 행 axis=0열
# row_sums = ar3.mean(axis=1)
# print(row_sums)
print(ar3)
print(ar3[0].mean())
print(ar3[1].mean())
print(ar3[2].mean())
for i in range(3):
    print(ar3[i].mean())

[[4 8 9]
 [8 7 4]
 [1 7 5]]
7.0
6.333333333333333
4.333333333333333
7.0
6.333333333333333
4.333333333333333


In [269]:
# 5. 행렬 곱셈 및 정규화
# 3*3 단위 행렬을 생성
# 다른 3*3 행렬을 만들어 행렬의 곱
ar4 = np.eye(3)
ar5 = np.full((3,3),2)
ar4*ar5

array([[2., 0., 0.],
       [0., 2., 0.],
       [0., 0., 2.]])