In [5]:
import numpy as np

c = np.array([1,2,3,4])
c.shape = (2,2)
c.shape = (4,)
c

array([1, 2, 3, 4])

In [ ]:
ar = np.array([True, False, True, False], dtype=np.int32)

ar.dtype

dtype('int32')

In [ ]:
# 1. 숫자 15에서 23까지 배열을 만들고 이를 3*3 행렬로 변환하여 출력하라
array = np.arange(15, 24).reshape(3, 3)
array

array([[15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [17]:
#2. 다음의 두 array를 만들고 위의 두 array를 이용해서 아래와 같은 값이 나오게
#   -[1,2,3,4]
#   -[5,6,7,8]
#목표 : [False,False,False,False]

# 두 array 생성
array1 = np.array([1, 2, 3, 4])
array2 = np.array([5, 6, 7, 8])

# 두 array를 비교하여 False 값 생성
result = array1 == array2
result


array([False, False, False, False])

In [18]:
# 3. 아래와 같이 3학생의 중간고사 점수, 기말고사 점수, 과제점수가 있다.
# (철수, 영희, 민재)
# 중간고사 = (15, 100, 45)
# 기말고사 = (78, 25, 90)
# 과제 = (81, 45, 99)

# 각 중간, 기말, 과제점수의 가중치를 각각 0.4 0.4 0.2를 부여하여 가중치의 합을
# 구하고, 거기에 기타점수 5점을 더하고자 한다.

# 학생들의 점수
중간고사 = np.array([15, 100, 45])
기말고사 = np.array([78, 25, 90])
과제 = np.array([81, 45, 99])

# 가중치
가중치 = np.array([0.4, 0.4, 0.2])

# 1) 중간고사 평균과 표준편차 계산
중간고사_평균 = np.mean(중간고사)
중간고사_표준편차 = np.std(중간고사)

print(f"중간고사 평균: {중간고사_평균}")
print(f"중간고사 표준편차: {중간고사_표준편차}")

# 2) 철수의 최종 점수 계산
최종점수 = 중간고사 * 가중치[0] + 기말고사 * 가중치[1] + 과제 * 가중치[2] + 5
철수_최종점수 = 최종점수[0]

print(f"철수의 최종 점수: {철수_최종점수}")

중간고사 평균: 53.333333333333336
중간고사 표준편차: 35.19785346990479
철수의 최종 점수: 58.400000000000006
